### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by lucacorti**
This cleans up dependecies and updates them. Do you think you could release an update?

### CODE REVIEW

**Comment by LostKobrakai** [comment]
Can you explain the switch to the much older and iirc broke `0.3` version of briefly? Also I'm wondering how those dependencies matter to you, given both dependencies do not affect downstream users of the library.

**Comment by lucacorti** [comment]
Sorry, I was trying to bring dependency up to date, I didn't notice the tag you wer pointing to was unreleased.
I guess updating ex_doc is possible anyway.

Actually, I'm trying to use depot_s3 which depends on an old depot release. I'll send a PR to update depot_s3.

**Comment by LostKobrakai** [comment]
depot_s3 is pointing to an old release for a reason. It does not yet support all the callbacks added in the latest depot version.

**Comment by lucacorti** [comment]
Ok, so I should just depend on depot_s3 I guess. Thanks.

**Pull request closed without merging**
